name: Testing

on:
  push:
    branches:
      - master

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Verify Go
        run: go version
      - name: Build
        run: |
          go build -ldflags="-s -w" ./example

  clientForWindows:
    name: Client (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Verify Go
        run: go version
      - name: Build
        run: |
          go build -ldflags="-s -w" ./example

  clientForLinux:
    name: Client (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev libasound2-dev libxxf86vm-dev
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Verify Go
        run: go version
      - name: Build
        run: |
          go build -ldflags="-s -w" ./example

  clientForMacOSamd64:
    name: Client (MacOS amd64)
    runs-on: macos-latest-large
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Verify Go
        run: go version
      - name: Build
        run: |
          go build -ldflags="-s -w" ./example

  clientForMacOSarm64:
    name: Client (MacOS arm64)
    runs-on: macos-latest-xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Verify Go
        run: go version
      - name: Build
        run: |
          go build -ldflags="-s -w" ./example